### PR TITLE
add data-testId attributes

### PR DESCRIPTION
**Pull request by JamesPHoughton**
I'm not sure yet how to build and test this myself, so this is more of a sketch of some desired functionality rather than a tested piece of code. Accompanies https://github.com/empiricaly/empirica/issues/161

### CODE REVIEW

**Comment by JamesPHoughton** [comment]
I've run this locally and see that it behaves as I expect. Ready for a review, @npaton

**Review by npaton — DISMISSED** [review]
LGTM

**Comment by JamesPHoughton** [comment]
Thanks! Looks like there is a `yarn.lock` conflict, and also that I'm not authorized to merge the PR.

**Comment by npaton** [comment]
Thank you for your contribution @JamesPHoughton!

I will try to maintain these the best I can, but let me know if any update breaks this.

In the long run, we will probably adopt a different "model" here, as we will likely rewrite the admin and potentially have different views. But I think it would be nice for us to keep enabling automated tests to be able to manipulate the admin.

One improvement we might want to consider is to use `data-` attributes: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes.

**Pull request merged**
