### PR TITLE
Add end to end tests with cypress

### PR DESCRIPTION
**Pull request by JamesPHoughton**
@npaton @amaatouq - I've modified some of the tests we're using in https://github.com/Watts-Lab/deliberation-empirica to run with the empirica template experiment. I'm happy to continue adding to these as we develop more features. 

Right now I have a separate GH action running so that I could test in my fork, but in the long run, it might make more sense to include the tests as part of your normal workflow to push to firebase.

Another thing i'd like to add to these tests is to push the `empirica_base` stage from `tests/Dockerfile` to dockerhub when the e2e tests pass. Then in our project, I can build our images on a base image from dockerhub instead of installing empirica as part of the Dockerfile build. If you can add me to the dockerhub organization (https://hub.docker.com/u/jamesphoughton) I'm happy to set that up.

### CODE REVIEW

**Comment by JamesPHoughton** [comment]
Also, it would be helpful to create a [cypress dashboard](https://www.cypress.io/) account and record test runs there - right now I have that part of the code commented out. It requires us to:
- [ ] add a `CYPRESS_RECORD_KEY` secret from the cypress dashboard to `.github/workflows/e2e.yaml`
- [ ] set `record: true` in the cypress action parameters
- [ ] modify line 2 of `test/cypress.config.js` to include the project id from the cypress dashboard `  projectId: '<id goes here>',`

**Comment by JamesPHoughton** [comment]
You'll notice that two of the tests fail. I believe these are associated with the phantom batches we were working on here: https://github.com/empiricaly/empirica/issues/112#issuecomment-1151648586

**Comment by npaton** [comment]
Wow, very cool! I created the Cypress org and invited you. Having e2e tests is really something we want, but I hadn't put any thought into how it would happen yet. It is an amazing initiative, thank you so much. While I would normally take time to plan, reflect, ponder, and ultimately waste time, I think I will be merging this very soon, and just see how it goes. We can evolve this over time, it looks like a great start! 🙌

**Comment by JamesPHoughton** [comment]
Sweet! I'll slack you the `CYPRESS_RECORD_KEY`, then we should be rolling. =)

**Comment by JamesPHoughton** [comment]
@npaton I think we still need to give approval for this action to run in the PR - for some reason, it won't run when I update the PR. (https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

**Comment by npaton** [comment]
Hey James. We're working on a new set of tests inspired by your work here. I apologize for not having merged this. We must have these tests. But since this PR was pushed, the core libraries have changed dramatically. Knowing that the API might change back then, I figured it was better to wait. We have also decided to go with Playwright instead of Cypress, as it better fits our needs. In the end, it made sense to restart this work from scratch.

You can follow along with the plan for our first tests here: https://github.com/empiricaly/empirica/issues/185
And the PR with the very first new e2e tests: https://github.com/empiricaly/empirica/pull/186/files

We're thankful for any feedback you might have about our plans. 🙏

**Pull request closed without merging**
